### ISSUE TITLE
Generated code is bloated and difficult to read

### ISSUE THREAD

**Issue by batiste** [batiste/pug-vdom#11]
`[].reduce(function(finalObj, currObj){ for (var propName in currObj) {finalObj[propName] = propName === "class" ? (finalObj[propName] ? finalObj[propName].concat(currObj[propName]) : [currObj[propName]]) : currObj[propName]; } return finalObj; }, {`

This code is repeating itself again and again. I have 2 suggestions:

 1. Introduce a function in the generated code and use it
 2. Do not generate this code on a empty array?

**Comment by batiste** [comment]
@Gryphon Myers what do you think of this?

**Comment by gryphonmyers** [comment]
Yes, sorry I did have cleaning this up on my mental to-do list. Both good suggestions, and using template literals would also allow for more consistent indentation. I will take improve this when I get a moment.

**Comment by gryphonmyers** [comment]
> Introduce a function in the generated code and use it

Thinking about this suggestion, it occurred to me that we could reduce bloat overall by introducing a small runtime library. How do you feel about that idea?

**Comment by batiste** [comment]
@gryphonmyers yeah I would introduce a runtime lib, that sounds like a great idea. Maybe use an external file for this so can be tested easily.

**Comment by batiste** [comment]
Thanks for the great contribution and tests 👍
