### ISSUE TITLE
Extends not supported

### ISSUE THREAD

**Issue by gryphonmyers** [batiste/pug-vdom#13]
I see that a comment was left in place of extends functionality. Are there any complications or issues to be aware of? Has this feature been attempted at all yet?

**Comment by batiste** [comment]
Extends is fully supported AFAIK because this is an abstraction that is resolved before our compiler by "pug-load". Includes an Extends are mostly statically compiled before hand into the AST

**Comment by gryphonmyers** [comment]
Not sure, I assumed it wasn’t due to the comment in the codebase. I will need to check

**Comment by gryphonmyers** [comment]
I have confirmed that extends are working as expected. I did need to expose pug loader options via ac02363b4379737f6d987d6610c576e6565ab2d8
