### ISSUE TITLE
while-loop not supported

### ISSUE THREAD

**Issue by matejcik** [batiste/pug-vdom#21]
Pug's `while` loop does not work.
```Error: Node not handled: While```

(Otherwise kudos for this project! I'm working on better Pug integration for Vue.js and this was the missing piece. The usual method was basically "use Pug to generate HTML, then process HTML with Vue's compiler", which is stupid and can't actually use Pug's templating features.)

**Comment by gryphonmyers** [comment]
Yes Vue's "support" of pug is not useful.

I will work on adding this if I find time

**Comment by gryphonmyers** [comment]
PR here https://github.com/batiste/pug-vdom/pull/23
